# -*- coding: utf-8 -*-
"""Example_batch_Mutation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImZD84513VRXDeLhL4uqb_wTwGbvMSRv

# **install_library**
"""

import pandas as pd
import numpy as np

"""# **data_upload**

mount_gdrive
"""

from google.colab import drive
drive.mount('/content/drive')

"""import_file"""

df = pd.read_table("/content/drive/MyDrive/LongReport_WeeklyAnalysis/WA22_16092021/MD_16092021.tsv", sep='\t')

"""# **data_clean**"""

#dataNeed_Strain_Date_Division_Location_Submitting_Lab_Region_Type_Clade_Lineage_ImpLin_VariantStatus

df.head(2)

"""delete_unnessary_columns_change_in_dataset"""

df.drop([ 'virus','gisaid_epi_isl', 'genbank_accession', 'region', 'country', 'region_exposure', 'country_exposure', 'division_exposure', 'segment', 'length', 'host', 'originating_lab', 'authors', 'url',
       'title', 'paper_url', 'date_submitted', 'purpose_of_sequencing', 'lab_id', 'totalInsertions', 'totalMissing', 'totalNonACGTNs', 'nonACGTNs', 'substitutions', 'deletions', 'aaDeletions', 'scorpio_call', 'note', 'pangoLEARN_version'], axis=1, inplace=True)
df.head(2)

"""# Lineage_Name_Change"""

#focus on other

df.loc[df['lineage'] == 'B.1.1.7', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.1', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.2', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.3', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.4', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.5', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.6', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.7', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'Q.8', 'ImpLin'] = 'Alpha'
df.loc[df['lineage'] == 'B.1.351', 'ImpLin'] = 'Beta'
df.loc[df['lineage'] == 'P.1', 'ImpLin'] = 'Gamma'
df.loc[df['lineage'] == 'B.1.525', 'ImpLin'] = 'Eta'
df.loc[df['lineage'] == 'B.1.526', 'ImpLin'] = 'Iota'
df.loc[df['lineage'] == 'B.1.617.1', 'ImpLin'] = 'Kappa'
df.loc[df['lineage'] == 'C.37', 'ImpLin'] = 'Lambda'
df.loc[df['lineage'] == 'B.1.621', 'ImpLin'] = 'Mu'
df.loc[df['lineage'] == 'B.1.427', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.429', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'R.1', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.466.2', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.1.318', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.1.519', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'C.36.3', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.214.2', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.1.523', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.619', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.620', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'C.1.2', 'ImpLin'] = 'Monitoring'
df.loc[df['lineage'] == 'B.1.617.2', 'ImpLin'] = 'Delta'
df.loc[df['lineage'] == 'AY.1', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.2', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.3', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.3.1', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.4', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.5', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.5.1', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.5.2', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.6', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.7', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.7.1', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.7.2', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.8', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.9', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.10', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.11', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.12', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.13', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.14', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.15', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.16', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.17', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.18', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.19', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.20', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.21', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.22', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.23', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.24', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.25', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.26', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.27', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.28', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.29', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.30', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.31', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.32', 'ImpLin'] = 'AY.X'
df.loc[df['lineage'] == 'AY.33', 'ImpLin'] = 'AY.X'
df.loc[(df['lineage'] != 'B.1.1.7') & (df['lineage'] != 'Q.1') & (df['lineage'] != 'Q.2') & (df['lineage'] != 'Q.3') & (df['lineage'] != 'Q.4') & (df['lineage'] != 'Q.5') & (df['lineage'] != 'Q.6') & (df['lineage'] != 'Q.7') & (df['lineage'] != 'Q.8') & (df['lineage'] != 'B.1.351') & (df['lineage'] != 'P.1') & (df['lineage'] != 'B.1.525') & (df['lineage'] != 'B.1.526') & (df['lineage'] != 'B.1.617.1') & (df['lineage'] != 'C.37') & (df['lineage'] != 'B.1.621') & (df['lineage'] != 'B.1.427') & (df['lineage'] != 'B.1.429') & (df['lineage'] != 'R.1') & (df['lineage'] != 'B.1.466.2') & (df['lineage'] != 'B.1.1.318') & (df['lineage'] != 'B.1.1.519') & (df['lineage'] != 'C.36.3') & (df['lineage'] != 'B.1.214.2') & (df['lineage'] != 'B.1.1.523') & (df['lineage'] != 'B.1.619') & (df['lineage'] != 'B.1.620') & (df['lineage'] != 'C.1.2') & (df['lineage'] != 'B.1.617.2') & (df['lineage'] != 'AY.1') & (df['lineage'] != 'AY.2') & (df['lineage'] != 'AY.3') & (df['lineage'] != 'AY.3.1') & (df['lineage'] != 'AY.4') & (df['lineage'] != 'AY.5') & (df['lineage'] != 'AY.5.1') & (df['lineage'] != 'AY.5.2') & (df['lineage'] != 'AY.6') & (df['lineage'] != 'AY.7') & (df['lineage'] != 'AY.7.1') & (df['lineage'] != 'AY.7.2') & (df['lineage'] != 'AY.8') & (df['lineage'] != 'AY.9') & (df['lineage'] != 'AY.10') & (df['lineage'] != 'AY.11') & (df['lineage'] != 'AY.12') & (df['lineage'] != 'AY.13') & (df['lineage'] != 'AY.14') & (df['lineage'] != 'AY.15') & (df['lineage'] != 'AY.16') & (df['lineage'] != 'AY.17') & (df['lineage'] != 'AY.18') & (df['lineage'] != 'AY.19') & (df['lineage'] != 'AY.20') & (df['lineage'] != 'AY.21') & (df['lineage'] != 'AY.22') & (df['lineage'] != 'AY.23') & (df['lineage'] != 'AY.24') & (df['lineage'] != 'AY.25') & (df['lineage'] != 'AY.26') & (df['lineage'] != 'AY.27') & (df['lineage'] != 'AY.28') & (df['lineage'] != 'AY.29') & (df['lineage'] != 'AY.30') & (df['lineage'] != 'AY.31') & (df['lineage'] != 'AY.32') & (df['lineage'] != 'AY.33'), 'ImpLin'] = 'Other'

#variant_naming

df.loc[df['ImpLin'] == 'Alpha', 'Variant'] = 'VOC'
df.loc[df['ImpLin'] == 'Beta', 'Variant'] = 'VOC'
df.loc[df['ImpLin'] == 'Gamma', 'Variant'] = 'VOC'
df.loc[df['ImpLin'] == 'Delta', 'Variant'] = 'VOC'
df.loc[df['ImpLin'] == 'Eta', 'Variant'] = 'VOI'
df.loc[df['ImpLin'] == 'Iota', 'Variant'] = 'VOI'
df.loc[df['ImpLin'] == 'Kappa', 'Variant'] = 'VOI'
df.loc[df['ImpLin'] == 'Lambda', 'Variant'] = 'VOI'
df.loc[df['ImpLin'] == 'Mu', 'Variant'] = 'VOI'
df.loc[df['ImpLin'] == 'Monitoring', 'Variant'] = 'Monitoring'
df.loc[(df['ImpLin'] != 'Alpha') & (df['ImpLin'] != 'Beta') & (df['ImpLin'] != 'Gamma') & (df['ImpLin'] != 'Delta') & (df['ImpLin'] != 'Eta') & (df['ImpLin'] != 'Iota') & (df['ImpLin'] != 'Kappa') & (df['ImpLin'] != 'Lambda') & (df['ImpLin'] != 'Mu') & (df['ImpLin'] != 'Monitoring'), 'Variant'] = 'Other'

df.head(2)

#date_format_change

df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df.head(2)

#amino_acid_explode

df['aaSubstitutions']=df['aaSubstitutions'].map(str)
df['aaSubstitutions'] = df['aaSubstitutions'].str.split(',')
mut1 = df.explode('aaSubstitutions')
mut1 = df.explode('aaSubstitutions')
mut1[['gene', 'aaMutations']] = mut1['aaSubstitutions'].str.split(':', expand=True)
mut1.head(1)

#mutation_split

mut2 = mut1['aaMutations'].str.split('(\d+)([A-Za-z]+)', expand=True)
mut3 = pd.concat([mut1, mut2], axis=1, join='inner')
mut3.rename(columns={0:'RefAA', 1:'Position', 2:'AltAA'}, inplace=True)
mut3.drop(3, axis=1, inplace=True)
mut3.head(2)

mut3.to_csv('mutation.csv', index=False)

#Select_Specific_gene

#full_specific_gene_download

S_gene=mut3[mut3['gene'] == 'S']
S_gene.to_csv('S_geneFull.csv', index=False)
S_gene.head(1)

#year_wise_specific_gene_down

#S_gene=mut3[mut3['gene'] == 'S']
#pd.crosstab([S_gene.gene, S_gene.year, S_gene.ImpLin, S_gene.aaMutations], S_gene.month, margins=True).head()

#pd.crosstab([S_gene.gene, S_gene.year, S_gene.ImpLin, S_gene.aaMutations], S_gene.month, margins=True).to_csv('S_gene_yr_iLin.csv')

#year_importantLineage_division_specific_gene_download

#S_gene=mut3[mut3['gene'] == 'S']
#pd.crosstab([S_gene.gene, S_gene.year, S_gene.ImpLin, S_gene.division, S_gene.aaMutations], S_gene.month, margins=True).head()

#pd.crosstab([S_gene.gene, S_gene.year, S_gene.ImpLin, S_gene.division, S_gene.aaMutations], S_gene.month, margins=True).to_csv('S_gene_yr_iLin_div.csv')

#mut3.to_csv('Mutation_split.csv', index=False)